version: "3.9" 
services:
  app:
    build: .
    container_name: rentx
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
#       - logvolume01:/var/log
#     depends_on:
#       - redis
#   redis:
#     image: redis
# volumes:
#   logvolume01: {}